name: CVE Scanning

on:
  push:
    paths:
      - 'requirements.txt'
      - 'safety-policy.yml'
      - '.github/workflows/cve-scanning.yml'

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  scan:
    name: Scan for CVEs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install safety
        run: pip3 install safety
      - name: Scan CVEs
        run: safety check -r requirements.txt --full-report --policy-file safety-policy.yml
