name: License Scanning

on:
  push:
    paths:
      - 'requirements.txt'
      - '.github/workflows/license-scanning.yml'

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
  IGNORE_LICENSES: "MIT License;Apache Software License;BSD License"
  # IGNORE_PACKAGES: ""

jobs:
  scan:
    name: Scan for licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pip-licenses
        run: pip3 install pip-licenses
      - name: Scan for licenses
        run: pip-licenses --allow-only="{{ $IGNORE_LICENSES }}" # --ignore-packages="{{ $IGNORE_PACKAGES }}"
